=== dpapageo/okstra-2018-classes/src/main/resources/lib/oklabi/schema/profile/1.0/profil.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
    targetNamespace="http://www.okstra.de/profile/1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:profile="http://www.okstra.de/profile/1.0">
    <xsd:element name="profile">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="profile:profil"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="profil">
        <xsd:complexType>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="profile:paket"/>
                <xsd:element ref="profile:tabelle"/>
                <xsd:element ref="profile:koordrefsys"/>
                <xsd:element ref="profile:fbliste"/>
            </xsd:choice>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="modellversion" type="xsd:string" use="required"/>
            <xsd:attribute name="modell" default="OKSTRA">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="OKSTRA"/>
                        <xsd:enumeration value="IDMVU"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="koordrefsys">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="fbliste">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="paket">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="1">
                <xsd:element ref="profile:objektarten"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="objektarten">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="profile:objektart"/>
            </xsd:sequence>
            <xsd:attribute name="auswahl" default="alle">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="alle"/>
                        <xsd:enumeration value="einige"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="objektart">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="profile:eigenschaft"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="weg" type="xsd:boolean" default="0"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="eigenschaft">
        <xsd:complexType>
            <xsd:choice>
                <xsd:element ref="profile:eigenschaft" minOccurs="0"
                    maxOccurs="unbounded"/>
                <xsd:element ref="profile:werte" minOccurs="0"
                    maxOccurs="1"/>
                <xsd:element ref="profile:objektarten" minOccurs="0"
                    maxOccurs="1"/>
            </xsd:choice>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
            <xsd:attribute name="min" type="xsd:integer"/>
            <xsd:attribute name="max" type="xsd:integer"/>
            <xsd:attribute name="fachid" default="beides">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="nur Fachkennungen"/>
                        <xsd:enumeration value="nur Objektinstanzen"/>
                        <xsd:enumeration value="beides"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="wert">
        <xsd:complexType>
            <xsd:sequence minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="profile:text"/>
            </xsd:sequence>
            <xsd:attribute name="kennung" type="xsd:string"
                use="required"/>
            <xsd:attribute name="weg" type="xsd:boolean" default="0"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="werte">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="unbounded">
                <xsd:element ref="profile:wert"/>
            </xsd:sequence>
            <xsd:attribute name="auswahl" default="alle">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="alle"/>
                        <xsd:enumeration value="einige"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>	
    <xsd:element name="tabelle">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="1">
                <xsd:element ref="profile:werte"/>
            </xsd:sequence>
            <xsd:attribute name="name" type="xsd:string" use="required"/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="text">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="name" type="xsd:string"
                        use="required"/>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== dpapageo/okstra-2018-classes/src/main/resources/lib/oklabi/profile/profil.xml
<?xml version="1.0" encoding="UTF-8"?>
<profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.okstra.de/profile/1.0 http://www.okstra.de/schema/profile/1.0/profil.xsd"
    xmlns="http://www.okstra.de/profile/1.0">
    <profil name="Beispielprofil_1.015" modellversion="1.015" modell="OKSTRA">
        <paket name="S_Strassennetz">
            <objektarten auswahl="alle">
                <objektart name="Strasse">
                    <eigenschaft name="hat_Strassenbezeichnung">
                        <eigenschaft name="Strassenklasse">
                            <werte auswahl="einige">
                                <wert kennung="A"/>
                                <wert kennung="B"/>
                                <wert kennung="S"/>
                            </werte>
                        </eigenschaft>
                    </eigenschaft>
                </objektart>
                <objektart name="Verbotene_Fahrbeziehung_NP"
                    weg="1"/>
                <objektart name="Abschnitt">
                    <eigenschaft name="dargestellt_von_Linie" min="1"
                        max="1"/>
                </objektart>
                <objektart name="Ast">
                    <eigenschaft name="dargestellt_von_Linie" min="1"
                        max="1"/>
                </objektart>
            </objektarten>
        </paket>
        <paket name="S_Entwurf">
        </paket>
        <paket name="S_Allgemeine_Geometrieobjekte">
        </paket>
        <paket name="S_Geometrieschema">
        </paket>
        <paket name="S_Historisierung">
        </paket>
        <tabelle name="Quelle_der_Information_Land">
            <werte auswahl="einige">
                <wert kennung="05">
                    <text name="Langtext">Deutsche Bahn AG</text>
                </wert>
                <wert kennung="06">
                    <text name="Langtext">Wasser- und Schifffahrtsverwaltung des Bundes</text>
                </wert>
            </werte>
        </tabelle>
        <tabelle name="Knotenpunktsystem">
            <werte>
                <wert kennung="00" weg="1"/>
            </werte>
        </tabelle>
        <koordrefsys name="DE_DHDN_3GK4"/>
        <fbliste name="Brandenburg 2.0"/>
    </profil>
    <profil name="Beispielprofil_1.014" modellversion="1.014">
    </profil>
    <profil name="Beispielprofil_1.011" modellversion="1.011" modell="OKSTRA">
        <paket name="Strassennetz">
            <objektarten auswahl="alle">
                <objektart name="Strasse">
                    <eigenschaft name="hat_Strassenbezeichnung">
                        <eigenschaft name="Strassenklasse">
                            <werte auswahl="einige">
                                <wert kennung="A"/>
                                <wert kennung="S"/>
                            </werte>
                        </eigenschaft>
                    </eigenschaft>
                </objektart>
                <objektart name="Verbotene_Fahrbeziehung"
                    weg="1"/>
                <objektart name="Abschnitt">
                    <eigenschaft name="dargestellt_von_Linie" min="1"
                        max="1"/>
                </objektart>
                <objektart name="Ast">
                    <eigenschaft name="dargestellt_von_Linie" min="1"
                        max="1"/>
                </objektart>
            </objektarten>
        </paket>
        <paket name="Entwurf">
        </paket>
        <paket name="Allgemeine_Geometrieobjekte">
        </paket>
        <paket name="Geometrieschema">
        </paket>
        <!--tabelle name="Baulast_Dritter">
            <werte auswahl="einige">
                <wert kennung="05">
                    <text name="Langtext">Deutsche Bahn AG</text>
                </wert>
                <wert kennung="06">
                    <text name="Langtext">Wasser- und Schifffahrtsverwaltung des Bundes</text>
                </wert>
            </werte>
        </tabelle-->
        <tabelle name="Knotenpunktsystem">
            <werte>
                <wert kennung="17" weg="1"/>
            </werte>
        </tabelle>
    </profil>
</profile>
